apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-serv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: microservices-music-store.dev
      http:
        paths:
          - path: /api/users/?(.*)
            backend:
              serviceName: auth-serv
              servicePort: 3000
          # client will always be last because regex is catch all
          - path: /?(.*)
            backend:
              serviceName: client-serv
              servicePort: 3000
